// Trending Malay TikTok affiliate hooks, scraped from hook-affiliate
// (Firestore `hooks`, 451 hooks / 9 categories, 2026-07-06). Used to seed
// real category-matched hooks into caption + master-plan generation so the
// AI opens with proven viral lines instead of generic patterns.
//
// Source of truth: HOOK_BANK.json at the repo root (regenerate this file from
// it if the bank is refreshed).

export type HookCategory =
  | "trending"
  | "makanan"
  | "skincare"
  | "kesihatan"
  | "pertanian"
  | "gadget"
  | "automotif"
  | "perfume"
  | "fashion";

export const HOOK_BANK: Record<HookCategory, string[]> = {
  trending: [
    "Seller ni memang tak bagi peluang 😭🛒",
    "Patutlah ramai berebut beli ni 😱📦",
    "Sekali tengok harga terus rasa nak beli 😆🛒",
    "Seller tiba-tiba baik hati pulak 😍🔥",
    "Last call sebelum harga naik balik 😭⏳",
    "Eh tiba-tiba promo muncul pulak 😳🔥",
    "FYP bagi petanda kena tengok ni 😍✨",
    "Harga macam ni buat tangan gatal 😆🛒",
    "Ramai beli sebab harga dia cantik 😳🛒",
    "Baru nak fikir seller bagi murah 😆🛒",
    "Baru nak simpan stok dah susut 😭📦",
    "Ramai dah masuk cart diam-diam 😳🛒",
    "Sekali tengok terus jatuh hati 😍✨",
    "Yang ni tengah orang cari 😳🔥",
    "Seller bagi deal macam nak habis 😭🔥",
    "Yang ni memang ramai yang repeat order 😳✨",
    "Yang ni memang selalu cepat habis 😳🔥",
    "Tak sangka benda ni murah gila 😱💸",
    "Nak beli nanti nanti harga naik 😭📈",
    "Jangan tunggu harga naik 😭📈",
    "Harga ni macam seller silap letak 😆💸",
    "Harga hari ni memang padu 😍🔥",
    "Stok makin cepat habis 😭📦",
    "Ramai baru perasan benda ni 😳🔥",
    "Tak beli sekarang nanti menyesal 😭⏳",
    "Barang viral ni memang laju 😍📦",
    "Murah macam ni memang susah jumpa 😭💸",
    "Harga macam ni bukan selalu 😱💸",
    "Seller buat hal malam ni 😱🔥",
    "Seller tak bagi masa nak fikir 😆🛒",
    "Baru masuk FYP terus kena racun 😆🛒",
    "Jangan scroll harga cantik ni 😍🛒",
    "Tunggu apa lagi promo jalan 😍🔥",
    "Deal macam ni jarang jumpa 😱💸",
    "Seriuslah harga ni macam tak betul 😭💸",
    "Alamak seller turun harga pulak 😱🔥",
    "Ingat nak scroll sekali tersangkut 😍🔥",
    "Trending sebab memang berbaloi 😳✨",
    "Masuk cart dulu nanti fikir 😆🛒",
    "Last chance grab sekarang 😭🔥",
    "Eh harga turun lagi sekali 😳🔥",
    "Yang ni masuk cart pun dah lega 😆🛒",
    "Harga jatuh lagi apa tunggu 😭🔥",
    "Jangan tengok lama nanti habis 😭🔥",
    "Rugi kalau tak tengok 😭🔥",
    "Sekejap je stok susut 😱📦",
    "Eh seller buat harga pelik pulak 😱💸",
    "Murah macam ni memang rare 😱🔥",
    "Orang dah checkout awak masih fikir 😆🛒",
    "Jangan tunggu esok promo jalan hari ni 😍🔥",
    "Produk ni tengah laju orang grab 😍🔥",
    "Baru nak beli seller turun harga 😭🔥",
    "Jangan terlepas promo ni 😭🔥",
    "Siapa cepat dia dapat 😆🛒",
    "Baru buka apps terus nampak deal 😍💸",
    "Harga dia ni tak masuk akal 😳💸",
    "Jangan kata tak tahu promo tengah on 😍🔥",
    "Jangan scroll dulu ini deal rare 😱💸",
    "Ingatkan beli semalam murah, rupanya harini harga lagi murah weh 😭⏳",
    "Tak sempat fikir stok dah jalan 😳📦",
    "Barang ni laju gila 😳📦",
    "Seller tengah buat hal lagi 😱🔥",
    "Ramai share sebab promo dia padu 😳✨",
    "Barang simple tapi ramai cari 😍📦",
    "Stok tinggal sikit jangan buat rileks 😭📦",
    "Ramai dah grab awak bila? 😍🔥",
    "Kalau lambat sikit tinggal review 😭📦",
    "Orang dah borong awak bila? 😆🛒",
    "Korang tau tak benda ni tengah viral? 😳🔥",
    "Aku pun mula-mula ingat tipu je 😅🛒",
    "Serius aku menyesal tak beli awal 😭⏳",
    "Kenapa tak ada orang bagitau aku awal? 😩🔥",
    "Ni yang aku cari selama ni rupanya 😍✨",
    "Sekali try memang tak boleh stop 😆🔥",
    "Jangan buat silap macam aku dulu 😭💸",
    "Weh ada orang guna ni tak? 😳🛒",
    "Aku beli sebab tergoda review orang 😅✨",
    "Yang skip video ni memang rugi 😭🔥",
    "Dulu aku ingat mahal, rupanya tak 😳💸",
    "Tengok skali je terus tersangkut 😍🔥",
    "Ni bukan iklan tapi memang aku suka 😆✨",
    "Comment kalau korang pun rasa sama 😳🔥",
    "Aku dah lama cari yang macam ni 😭✨",
    "Jujur cakap, ni memang berbaloi 😍🛒",
    "Sekali cuba baru tau kenapa ramai puji 😳✨",
    "Korang selalu terlepas benda macam ni 😩🔥",
    "Bila dah try baru menyesal beli lambat 😭⏳",
    "Kawan aku suruh beli, memang tak tipu 😆🛒",
    "Ada benda simple macam ni pun aku baru tau 😳✨",
    "Ni antara yang paling berbaloi aku beli 😍💸",
    "Aku bagi je korang tau, jangan lambat 😭🔥",
    "Yang tunggu-tunggu selalu terlepas 😩📦",
    "Percaya tak, benda ni ubah rutin aku 😳✨",
    "Aku pun ingat ni gimmick, sekali salah 😅🔥",
    "Kalau korang teragak-agak, ni petanda 😍🛒",
    "Satu je aku boleh cakap — jangan skip 😭🔥",
    "Aku dah try banyak, ni paling okay 😳✨",
    "Bukan aku sorang yang cakap best 😆🔥",
    "Korang scroll, orang lain dah checkout 😩🛒",
    "Ni yang buat aku stop scroll malam tu 😳🔥",
    "Aku share sebab memang worth it 😍✨",
    "Yang lambat memang selalu nangis 😭📦",
    "Sekali guna terus rasa nak repeat 😆🔥",
    "Aku tak sangka impact dia besar macam ni 😳✨",
    "Kalau ada budget lebih, ni aku recommend 😍🛒",
    "Baru je viral dah ramai tanya link 😳🔥",
    "Aku beli untuk try, sekali jatuh cinta 😆✨",
    "Jangan tunggu orang lain beli baru nak percaya 😭🔥",
    "Ni memang jenis beli sekali guna lama 😍✨",
    "Korang deserve benda yang berbaloi ni 😳🛒",
    "Ada satu benda ni ramai tak perasan 👀🔥",
    "Rahsia kenapa ni laku gila 🤫🔥",
    "Tak ramai tahu pasal benda ni 🤫✨",
    "Jom aku bagitau kenapa ni special 👀🔥",
    "Benda kecil ni ada cerita disebaliknya 👀✨",
    "POV: korang jumpa benda yang tak tahu korang perlukan 😳✨",
    "POV: baru scroll dah tak boleh lupa 😵‍💫🔥",
    "POV: kawan tanya beli kat mana 😆🛒",
    "POV: dah masuk cart tanpa fikir panjang 🫣🛒",
    "Tip: kalau nampak ni, jangan fikir lama 😏🛒",
    "Nak jimat masa? Tengok ni dulu 😌⏳",
    "Satu tip je: jangan tunggu lama 😏🔥",
    "Cara paling senang — check benda ni dulu 😌✨",
    "Pernah tak rasa menyesal beli lambat? 🙃😭",
    "Korang jenis fikir lama sebelum beli tak? 🤔🛒",
    "Ada tak benda yang korang selalu tertunda beli? 🙈🛒",
    "Selalu ke terlepas benda viral macam ni? 😩🔥",
    "Kadang benda simple yang buat kita happy 😊✨",
    "Bila jumpa yang betul, memang terus tahu 😍✨",
    "Yang bagus memang tak payah convince pun 😌🔥",
    "Ada je benda yang worth setiap sen 💯🛒",
    "Jom aku citer kenapa aku beli ni 🗣️✨",
    "Nak share sikit pengalaman aku 🙌✨",
    "Cuba dengar dulu sebelum korang skip 🙏🔥",
    "Ni antara pembelian terbaik bulan ni 💯🔥",
    "Kalau nak jujur, ni memang game changer 😮‍💨✨",
    "Berbaloi ke tak? Aku cakap berbaloi 💯🛒",
    "Benda macam ni jarang aku recommend, tapi ni lain 😳✨",
    "Kalau aku boleh pusing masa, aku beli awal 😩⏳",
  ],
  makanan: [
    "Ramai repeat sebab senang jatuh suka 😳✨",
    "Kalau suka cuba rasa ini wajib tengok 😆🍔",
    "Makanan viral ni laju orang grab 😍📦",
    "Seller buat deal untuk kaki makan 😱🔥",
    "Ramai simpan cart sebab takut habis 😭📦",
    "Baru nampak promo terus nak checkout 😭🛒",
    "Stok makin susut sebab ramai repeat 😱📦",
    "Jangan tengok lama nanti lapar 😆🍫",
    "Jangan lepaskan promo sedap ni 😭🔥",
    "Eh makanan ni nampak sedap gila 😍🍔",
    "Sekali cuba nanti mungkin repeat 😍✨",
    "Yang ni sesuai buat stok rumah 😍📦",
    "Set makanan ni memang nampak padu 😍🔥",
    "Stok makanan ni cepat habis 😱📦",
    "Jangan scroll dulu ni memang menggoda 😆🍔",
    "Grab sekarang sementara promo 😭🍔",
    "Ramai beli untuk makan sambil santai 😳✨",
    "Ramai beli sebab rasa nak cuba 😳🛒",
    "Harga jimat rasa macam menang 😆💸",
    "Seller bagi deal untuk yang lapar 😭🛒",
    "Kalau suka manis ini boleh racun 😆🍫",
    "Baru buka parcel bau dah padu 😍🍔",
    "Eh set ni memang nampak puas hati 😍🔥",
    "Seller buat promo kejap je ni 😱🔥",
    "Ramai dah checkout awak bila? 😳🛒",
    "Jangan scroll dulu rasa dia memanggil 😆🍫",
    "Eh sedap macam ni harga pula cantik 😍✨",
    "Ramai order sebab nampak fresh 😍🍔",
    "Seller tengah bagi harga jimat 😭💸",
    "Baru tengok je perut terus bunyi 😭🍫",
    "Seller buat promo makanan viral 😍🔥",
    "Seller turun harga untuk set ni 😳💸",
    "Tak perlu fikir lama kalau dah lapar 😆🛒",
    "Ingat biasa rupanya ramai borong 😱📦",
    "Kalau lapar malam ini racun dia 😆🍫",
    "Yang ni nampak berbaloi sangat 😳🛒",
    "Packaging cantik isi pun nampak padu 😍✨",
    "Kalau nak cuba sekarang masa dia 😍🔥",
    "Jangan tunggu esok stok jalan hari ni 😱📦",
    "Yang suka snack kena tengok ni 😍🔥",
    "Patutlah ramai repeat order ni 😳🔥",
    "Kalau jumpa FYP ni itu petanda 😆🍔",
    "Produk makanan ni memang ramai tanya 😳🔥",
    "Makanan macam ni selalu cepat sold out 😭📦",
    "Promo ni memang buat tak senang duduk 😭🔥",
    "Harga macam ni buat lapar terus 😭💸",
    "Harga ni macam rezeki tengah lalu 😭💸",
    "Yang ni memang sesuai buat kudap 😳🍫",
    "Tak sangka harga boleh murah macam ni 😍💸",
    "Tak sangka makanan ni ramai cari 😱🔥",
  ],
  skincare: [
    "Baru tengok review terus rasa nak cuba 😆🛒",
    "Rutin malam jadi lebih best 😍🌙",
    "Kalau suka deal skincare tengok ni 😍✨",
    "Eh harga dia buat terkejut 😭💸",
    "Produk ni nampak mahal tapi jimat 😍✨",
    "Patutlah ramai repeat skincare ni 😳🔥",
    "Yang suka kulit nampak fresh tengok ni 😍🌸",
    "Alamak kulit kusam pun boleh nampak 😭✨",
    "Tak sangka set ni harga tengah turun 😳💸",
    "Set cantik macam ni memang ramai grab 😍🛒",
    "Seller turunkan harga kejap je ni 😳🔥",
    "Harga ni macam seller silap kira 😭💸",
    "Baru nak survey terus jumpa promo 😳🔥",
    "Harga promo ni bukan selalu 😭💸",
    "Rutin simple tapi nampak premium 😳✨",
    "Ramai cari rutin simple macam ni 😳✨",
    "Seller baik hati hari ni 😭🔥",
    "Ramai masuk cart sebab tengah promo 😳🛒",
    "Produk ni tengah naik dekat FYP 😱🔥",
    "Seller punya promo memang cun 😱🔥",
    "Produk self-care wajib tengok 😍✨",
    "Skincare ni memang mudah jatuh hati 😆🛒",
    "Skincare simple ni ramai suka 😳🌸",
    "Stok laju sebab ramai repeat 😱📦",
    "Ramai dah cuba awak bila? 😍🔥",
    "Kalau nampak ni simpan dulu 😳🛒",
    "Skincare viral ni selalu laju habis 😱📦",
    "Yang ni sesuai buat stok rutin 😍📦",
    "Beli sekarang kulit happy nanti 😆✨",
    "Jangan scroll dulu kulit pun nak manja 😆✨",
    "Seller buat deal untuk skincare ni 😱🔥",
    "Kalau suka glowing jangan skip ni 😍🔥",
    "Jangan tunggu habis baru nak cari 😭📦",
    "Eh packaging cantik harga pun cantik 😱✨",
    "Kalau nak mula rutin boleh tengok ni 😳🌸",
    "Kalau lambat stok tinggal cerita 😭📦",
    "Yang nak nampak fresh boleh mula sini 😍✨",
    "Yang suka self-care kena tengok ni 😍🌸",
    "Jangan tunggu kulit merajuk dulu 😆✨",
    "Skincare ni tengah ramai share 😍🔥",
    "Tak perlu banyak step mula yang simple 😳🌸",
    "Grab sekarang sebelum habis 😭🔥",
    "Ingat mahal rupanya seller promo 😍💸",
    "Packaging lawa harga pun lawa 😍✨",
    "Jangan lepaskan promo skincare ni 😭💸",
    "Bukan biasa-biasa ramai repeat 😍✨",
    "Ramai tanya link skincare ni 😳🔥",
    "Baru nak cuba seller turun harga 😭💸",
    "Ramai repeat sebab mudah masuk rutin 😳🌸",
    "Ramai beli sebab nampak berbaloi 😍🛒",
  ],
  kesihatan: [
    "Untuk yang nak mula rutin lebih baik 😍🌿",
    "Benda simple tapi ramai cari sekarang 😱🔥",
    "Seller bagi offer memang cantik 😳💸",
    "Untuk rutin harian ramai pilih ni 😍🌿",
    "Ramai kata berbaloi sebab mudah guna 😳✨",
    "Ramai beli untuk stok dekat rumah 😳📦",
    "Patutlah ramai repeat benda ni 😳✨",
    "Seller buat deal untuk jaga rutin 😱🔥",
    "Ramai simpan cart sebab tengah promo 😍🛒",
    "Tak perlu fikir lama kalau memang cari 😳🔥",
    "Ingat mahal rupanya seller buat promo 😱🔥",
    "Kalau sayang mak ayah tengok ni dulu ❤️✨",
    "Jangan tunggu nanti harga naik balik 😭📈",
    "Rutin kecil macam ni ramai suka 😍✨",
    "Sekali cuba rutin terus nak ulang 😳🌿",
    "Ramai pilih sebab nampak berbaloi 😍🛒",
    "Kalau selalu lupa jaga rutin, simpan ni 😳🛒",
    "Produk harian ni memang senang guna 😍✨",
    "Seller bagi harga cantik hari ni 😭💸",
    "Ramai cari bila nak mula rutin 😳🌿",
    "Mak ayah tengok ni mesti suka 😍❤️",
    "Mak ayah selalu cari produk macam ni 😭❤️",
    "Tak sangka harga boleh serendah ni 😱💸",
    "Seller turun harga untuk set ni 😭🔥",
    "Jangan skip kalau sayang badan sendiri ❤️🔥",
    "Yang sayang diri kena tengok ni 😍❤️",
    "Ramai repeat sebab senang diamalkan 😳✨",
    "Yang nak stok bulanan boleh grab ni 😳📦",
    "Yang ni ramai beli untuk keluarga ❤️📦",
    "Produk harian ni memang kena ada 😍🌿",
    "Jaga diri tak susah mula dengan ni 😍🌿",
    "Harga promo ni buat ramai grab 😱💸",
    "Jangan tunggu badan rasa tak best 😳🌿",
    "Rutin harian jadi lebih mudah 😍✨",
    "Jangan tunggu viral baru nak beli 😭🔥",
    "Seller punya promo memang ngam 😱🔥",
    "Ramai mula amalkan sebab mudah sangat 😍🌿",
    "Barang kesihatan ni memang ramai cari 😳🌿",
    "Jangan tunggu habis baru nak cari 😭🔥",
    "Kalau nak mula jaga rutin tengok ni 😳🌿",
    "Produk ni sesuai buat stok rumah 😍📦",
    "Stok kat rumah lagi senang hati 😆📦",
    "Bukan untuk orang lain untuk diri sendiri ❤️✨",
    "Ramai mula jaga diri dengan cara simple 😍✨",
    "Eh produk ni ramai sangat tanya 😱🔥",
    "Ini bukan trend ini keperluan 😍❤️",
    "Kalau jumpa deal ni jangan lepaskan 😍🔥",
    "Produk ni tengah ramai masukkan cart 😳🛒",
    "Set macam ni selalu cepat habis 😭📦",
    "Grab sekarang sementara promo 😭🔥",
  ],
  pertanian: [
    "Stok makin susut sebab ramai grab 😱📦",
    "Ramai beli sebab mudah digunakan 😳✨",
    "Jangan tunggu pokok merajuk dulu 😆🌱",
    "Pokok pun boleh nampak lebih terjaga 😳🌱",
    "Seller turunkan harga kejap je ni 😭💸",
    "Ramai dah cuba awak bila? 😳🔥",
    "Baru tengok hasil terus rasa nak cuba 😳🌱",
    "Pokok kecil pun perlukan rutin 😍🌿",
    "Ramai repeat untuk stok kebun 😳📦",
    "Barang kebun ni memang ramai tanya 😍🌿",
    "Patutlah ramai kebun cari ni 😳🔥",
    "Tanaman pun nak penjagaan baik 😍🌿",
    "Barang pertanian ni memang laju jalan 😱📦",
    "Promo macam ni jarang lalu FYP 😱🔥",
    "Jangan biar pokok kurang perhatian 😆🌿",
    "Kalau nak pokok happy tengok ni dulu 😆🌿",
    "Pokok nampak segar bila rutin betul 😍🌱",
    "Yang suka bercucuk tanam kena tengok ni 😍🌿",
    "Barang ni sesuai buat stok tanaman 😍📦",
    "Yang baru mula tanam boleh tengok ni 😆🌿",
    "Harga promo ni memang ngam 😱💸",
    "Ingat biasa rupanya ramai repeat 😱✨",
    "Yang ada kebun wajib tengok ni 😍🌿",
    "Tak sangka harga boleh turun macam ni 😱💸",
    "Seller buat hal harga turun 😭🔥",
    "Produk pertanian ni ramai cari sekarang 😳🔥",
    "Kalau tanam sendiri ini boleh bantu 🌱🔥",
    "Ramai beli sebab nampak praktikal 😍✨",
    "Kalau jumpa promo ambil dulu 😆🛒",
    "Kalau lambat stok tinggal cerita 😭🔥",
    "Stok pertanian ni selalu cepat habis 😭📦",
    "Tak perlu pening produk ni mudah guna 😳🌿",
    "Seller tengah clear stok kebun 😭📦",
    "Ramai simpan cart untuk pokok 😳🛒",
    "Grab sekarang untuk tanaman 😍🌱",
    "Seller turun harga untuk tanaman 😭💸",
    "Seller buat promo untuk kaki kebun 😱🔥",
    "Produk ni nampak simple tapi berguna 😍✨",
    "Jaga pokok jadi lebih mudah 😍🌱",
    "Jangan lepaskan deal kebun ni 😆🔥",
    "Ramai kaki kebun simpan link ni 😳🛒",
    "Seller bagi harga kaki kebun suka 😆💸",
    "Pokok nampak kemas bila dijaga 😍🌱",
    "Benda ni ramai kaki tanaman suka 😍🌱",
    "Jangan tunggu musim baru nak beli 😭🔥",
    "Kalau suka hasil cantik mulakan rutin 🌱✨",
    "Kalau sayang pokok jangan skip ni 🌱🔥",
    "Seller bagi deal jangan lepaskan 😱💸",
    "Untuk tanaman rumah pun boleh tengok 😍🌱",
  ],
  gadget: [
    "Gadget viral ni memang ramai cari 😳📱",
    "Stok gadget ni selalu cepat jalan 😱📦",
    "Jangan skip kalau suka gadget smart 😆🔥",
    "Deal macam ni jarang nampak 😭💸",
    "Harga turun lagi apa tunggu 😱💸",
    "Barang ni nampak kecil tapi membantu 😍📱",
    "Grab sekarang sebelum sold out 😭📦",
    "Ramai share sebab fungsi dia padu 😱🔥",
    "Tak perlu mahal asal berguna 😍📱",
    "Gadget ni memang patut ada satu 😆📱",
    "Harga macam ni memang berbaloi 😭💸",
    "Yang suka benda smart ini racun dia 😆🛒",
    "Ramai repeat beli untuk rumah juga 😳📦",
    "Barang kecil ni boleh settle kerja 😍📱",
    "Tak sangka benda ni boleh jadi viral 😳✨",
    "Ramai beli sebab nampak kemas 😍✨",
    "Promo gadget ni jangan lepaskan 😭🔥",
    "Eh benda ni patut beli awal 😭✨",
    "Seller punya harga memang ngam 😍🔥",
    "Baru buka TikTok terus kena racun 😆📱",
    "Tak sangka gadget ni laju orang grab 😱📦",
    "Seller turun harga untuk gadget ni 😭💸",
    "Kalau selalu sibuk kena tengok ni 😳📱",
    "Barang kecil tapi fungsi besar 😳🔥",
    "Fungsi dia simple tapi memang guna 😍✨",
    "Yang kerja harian boleh mudah sikit 😳📱",
    "Patutlah ramai checkout benda ni 😱🔥",
    "Harga dia tengah cantik sangat 😳💸",
    "Murah tapi fungsi nampak premium 😍✨",
    "Ramai baru tahu fungsi benda ni 😳✨",
    "Baru tengok demo terus nak beli 😍🔥",
    "Barang ni boleh jimat masa 😍⏳",
    "Ramai beli sebab senang pakai 😆🛒",
    "Kalau lambat sikit habis dulu 😭🔥",
    "Eh gadget kecil ni mudahkan kerja 😳📱",
    "Jangan tunggu review baru nak beli 😭🔥",
    "Ramai masuk cart lepas tengok demo 😳🛒",
    "Seller buat promo hari ni 😍🔥",
    "Seller tak bagi masa fikir lama 😭🔥",
    "Jangan tunggu nanti stok habis 😭📦",
    "Produk ni buat kerja jadi cepat 😳📱",
    "Kalau suka praktikal tengok ni dulu 😆🛒",
    "Jangan scroll dulu ni memang praktikal 😍📱",
    "Ini gadget yang buat hidup senang 😆✨",
    "Seller bagi deal buat tak boleh tahan 😆🔥",
    "Gadget ni nampak simple tapi padu 😱✨",
    "Yang ni bukan mainan memang berguna 😍✨",
    "Seller tengah clear stok ni 😱📦",
    "Ingat biasa rupanya berguna gila 😍✨",
  ],
  automotif: [
    "Stok automotif ni cepat susut 😱📦",
    "Promo automotif ni jarang nampak 😱💸",
    "Jangan skip kalau kereta selalu guna 🚗🔥",
    "Ramai simpan cart untuk kereta 😳🛒",
    "Kalau lambat sikit stok tinggal cerita 😱📦",
    "Seller bagi promo memang cantik 😍💸",
    "Kalau selalu drive benda ni membantu 😍🚗",
    "Aksesori ni tengah ramai cari 😱🔥",
    "Barang kecil tapi impak dia besar 😱✨",
    "Yang ni sesuai buat hadiah juga 😍🎁",
    "Seller clear stok cepat grab 😭📦",
    "Barang simple tapi buat kereta cantik 😍✨",
    "Kereta pun rasa lebih tersusun 😍🚗",
    "Aksesori kecil ni ramai tak tahu 😳🚗",
    "Seller punya harga memang ngam 😭🔥",
    "Kalau sayang kereta kena tengok ni 😆🚗",
    "Patutlah ramai beli aksesori ni 😳🔥",
    "Ramai beli sebab mudah pasang 😳🛠️",
    "Jangan tunggu rosak baru nak cari 😭🔥",
    "Grab sekarang owner kereta 😆🚗",
    "Kereta nampak kemas bila ada benda ni 😍🚗",
    "Owner kereta wajib check benda ni 😳🔥",
    "Kalau nampak murah ambil dulu 😭💸",
    "Harga dia tengah cantik sekarang 😳💸",
    "Kereta biasa pun boleh nampak kemas 😍🚗",
    "Ingat kecil rupanya berguna sangat 😱✨",
    "Yang suka kereta bersih jangan skip ni 😆✨",
    "Jangan scroll dulu owner kereta wajib tengok 🚗🔥",
    "Tak sangka barang ni boleh nampak premium 😳✨",
    "Ramai share sebab memang berguna 😳🛠️",
    "Ramai beli sebab nampak praktikal 😳🛠️",
    "Produk ni memang sesuai ada dalam kereta 🚗🔥",
    "Barang ni bukan gaya memang berguna 😍🛠️",
    "Seller bagi deal hari ni je 😱🔥",
    "Seller buat deal untuk kaki kereta 😆🔥",
    "Tak sangka benda ni buat kereta kemas 😍🚗",
    "Ramai repeat beli untuk kereta kedua 😳🚗",
    "Aksesori ni nampak simple tapi smart 😆✨",
    "Barang automotif ni selalu cepat habis 😱📦",
    "Jangan tengok je kereta pun nak manja 😆🚗",
    "Harga promo ni boleh masuk cart 😍🛒",
    "Promo terakhir jangan lepaskan 😭🔥",
    "Produk ni buat kereta nampak premium 😍✨",
    "Baru tengok demo terus rasa nak beli 😍🛒",
    "Kalau suka kemas ini memang sesuai 🚗✨",
    "Tak perlu mahal asal nampak kemas 😳✨",
    "Seller turun harga untuk kereta ni 😭💸",
    "Kereta nampak lain lepas tambah ni 😍✨",
  ],
  perfume: [
    "Yang suka wangi wajib simpan link 😆🛒",
    "Tak perlu fikir lama kalau dah suka bau 😆🌸",
    "Last chance untuk bau premium 😍🔥",
    "Baru tengok botol terus jatuh hati 😆🛒",
    "Grab sekarang sebelum sold out 😆🌸",
    "Seller bagi harga memang cun 😱💸",
    "Seller buat deal hari ni je 😳🔥",
    "Ramai dah checkout awak bila? 😳🔥",
    "Ingat mahal rupanya seller promo 😱💸",
    "Botol cantik harga pun cantik 😍✨",
    "Kalau suka wangi kena tengok ni 🌸🔥",
    "Tak sangka harga boleh semurah ni 😱💸",
    "Perfume ni tengah ramai cari 😳🌸",
    "Ramai beli untuk hadiah juga 😍🎁",
    "Bau wangi ni memang buat mood naik 😆✨",
    "Ramai masuk cart sebab review best 😍🛒",
    "Packaging cantik bau pun nampak premium 😳✨",
    "Perfume ni sesuai untuk daily use 😍🌸",
    "Jangan skip kalau nak bau kemas 😍🌸",
    "Yang ni nampak mahal tapi jimat 😍💸",
    "Produk ni nampak simple tapi premium 😍🔥",
    "Promo perfume ni jangan lepaskan 😭💸",
    "Perfume ni nampak premium sangat 😍✨",
    "Seller turun harga untuk scent ni 😭💸",
    "Harga promo ni bukan selalu 😱💸",
    "Eh bau macam mahal harga pula cantik 😍🌸",
    "Perfume ni sesuai pakai hari-hari 😍✨",
    "Scent macam ni memang mudah suka 😍✨",
    "Kalau suka scent clean ini pilihan 😆🌸",
    "Seller tak bagi masa nak fikir 😭🔥",
    "Perfume viral ni laju orang grab 😭📦",
    "Perfume macam ni senang masuk cart 😳🛒",
    "Ramai grab sebab stok tak banyak 😭📦",
    "Ramai beli sebab nampak berbaloi 😆🛒",
    "Ramai share sebab bau dia menarik 😳🔥",
    "Seller punya deal memang padu 😱🔥",
    "Yang suka bau fresh ini racun dia 😍🌸",
    "Jangan scroll dulu bau dia padu 😆🔥",
    "Stok perfume ni cepat susut 😭📦",
    "Kalau suka bau manis boleh tengok ni 😆🌸",
    "Ramai repeat sebab bau dia selesa 😳✨",
    "Kalau lambat sikit habis dulu 😳🔥",
    "Patutlah ramai repeat perfume ni 😳🔥",
    "Seller buat promo untuk kaki perfume 😱🔥",
    "Eh bau dia buat orang tanya 😳🌸",
    "Sekali spray terus rasa confident 😍✨",
    "Sekali nampak review terus nak cuba 😳🛒",
  ],
  fashion: [
    "Outfit ni nampak mahal tapi jimat 😍✨",
    "Jangan scroll dulu style dia padu 😆🔥",
    "Ramai repeat sebab material nampak best 😳✨",
    "Ramai beli untuk pakai keluar 😆👗",
    "Style ni sesuai untuk banyak acara 😍✨",
    "Baru tengok design terus rasa nak beli 😆🛒",
    "Outfit ni sesuai untuk daily wear 😍✨",
    "Kalau pakai ni terus nampak kemas 😍✨",
    "Outfit macam ni senang match 😳✨",
    "Outfit simple pun nampak mahal 😍👕",
    "Fashion viral ni memang laju jalan 😍🔥",
    "Stok size ni selalu cepat habis 😭📦",
    "Promo fashion ni jangan lepaskan 😭💸",
    "Seller turun harga untuk design ni 😭💸",
    "Design macam ni memang senang suka 😳🔥",
    "Ramai share sebab cutting nampak cantik 😳✨",
    "Sekali nampak review terus nak checkout 😳🛒",
    "Tak perlu fikir lama kalau dah berkenan 😆👕",
    "Yang suka OOTD kena tengok ni 😍📸",
    "Stok makin susut sebab ramai grab 😭📦",
    "Jangan skip kalau suka style simple 😍✨",
    "Fashion ni tengah ramai cari 😳👗",
    "Kalau jumpa size cepat grab 😆📦",
    "Yang suka bergaya wajib simpan link 😆🛒",
    "Ramai masuk cart sebab nampak cantik 😍🛒",
    "Kalau nak nampak kemas boleh cuba ni 😆👕",
    "Fashion ni nampak premium sangat 😍✨",
    "Ramai beli sebab senang pakai 😍✨",
    "Kalau suka look kemas ini memang ngam 😆👕",
    "Design simple tapi nampak premium 😍✨",
    "Jangan tunggu size habis dulu 😭📦",
    "Kalau lambat sikit size tinggal sikit 😳🔥",
    "Patutlah ramai checkout baju ni 😳🔥",
    "Seller tak bagi masa nak fikir 😭🛒",
    "Grab sekarang sebelum sold out 😆👕",
    "Tak sangka harga boleh cantik macam ni 😱💸",
    "Yang ni sesuai buat gift juga 😍🎁",
    "Seller buat promo untuk kaki OOTD 😱🔥",
    "Last chance untuk style cantik ni 😍🔥",
    "Eh warna dia cantik sangat 😳👗",
  ],
};

// Keyword → category map for inferring a product's niche from its name/
// description. First category whose keyword appears wins; else 'trending'.
const CATEGORY_KEYWORDS: [HookCategory, string[]][] = [
  ["skincare", ["serum", "lotion", "cream", "krim", "moisturizer", "cleanser", "toner", "sunscreen", "spf", "skincare", "jerawat", "muka", "kulit", "whitening", "glow", "cerah", "facial", "masker", "mask", "acne", "niacinamide", "retinol", "collagen mask"]],
  ["perfume", ["perfume", "minyak wangi", "wangi", "fragrance", "cologne", "scent", "eau de", "parfum", "bau badan", "body mist", "deodoran", "deodorant"]],
  ["makanan", ["makan", "makanan", "snack", "sambal", "kuih", "coklat", "biskut", "biscuit", "minuman", "kopi", "coffee", "food", "resepi", "sedap", "rangup", "drink", "jus", "mukbang", "keropok", "kerepek", "madu", "honey"]],
  ["kesihatan", ["supplement", "suplemen", "vitamin", "kesihatan", "sihat", "tenaga", "sendi", "urat", "herba", "herbal", "collagen", "detox", "stamina", "imun", "probiotik", "omega", "gummies", "booster"]],
  ["gadget", ["gadget", "phone", "telefon", "charger", "earbud", "earphone", "headset", "smartwatch", "elektronik", "usb", "powerbank", "power bank", "kamera", "camera", "wireless", "wayarles", "bluetooth", "tech", "projector", "speaker", "lampu led", "led", "robot"]],
  ["automotif", ["kereta", "car", "motor", "motosikal", "tayar", "enjin", "engine", "automotif", "brake", "dashcam", "vacuum kereta", "minyak hitam", "aksesori kereta", "vehicle", "truck", "van"]],
  ["pertanian", ["pokok", "tanam", "baja", "kebun", "pertanian", "benih", "tani", "sayur", "buah", "farm", "garden", "fertilizer", "racun serangga", "penyembur", "hidroponik"]],
  ["fashion", ["baju", "seluar", "tudung", "hijab", "kasut", "shoe", "beg", "bag", "fashion", "outfit", "dress", "jam tangan", "watch", "blouse", "jeans", "shirt", "kemeja", "abaya", "kurung", "cardigan", "jaket", "tshirt", "t-shirt", "kain"]],
];

export function inferHookCategory(text: string | undefined | null): HookCategory {
  const t = (text || "").toLowerCase();
  if (!t.trim()) return "trending";
  for (const [cat, words] of CATEGORY_KEYWORDS) {
    if (words.some((w) => t.includes(w))) return cat;
  }
  return "trending";
}

// Pick `n` distinct hooks from a category (falls back to trending when the
// category is empty). `seed` lets callers vary the picks per video without a
// global RNG — pass a stable per-item number (index, hash) for reproducible
// spread; omit for random.
export function pickHooks(
  category: HookCategory | string,
  n = 5,
  seed?: number
): string[] {
  const key = (HOOK_BANK as any)[category] ? (category as HookCategory) : "trending";
  const pool = HOOK_BANK[key].length ? HOOK_BANK[key] : HOOK_BANK.trending;
  if (pool.length <= n) return [...pool];
  const start =
    typeof seed === "number"
      ? Math.abs(Math.floor(seed)) % pool.length
      : Math.floor(Math.random() * pool.length);
  const out: string[] = [];
  for (let i = 0; i < n; i++) out.push(pool[(start + i * 7) % pool.length]);
  // de-dupe in case the stride collides on a short pool
  return Array.from(new Set(out)).slice(0, n);
}

// Convenience: infer category from product text, then pick hooks.
export function hooksForProduct(productText: string, n = 5, seed?: number): {
  category: HookCategory;
  hooks: string[];
} {
  const category = inferHookCategory(productText);
  return { category, hooks: pickHooks(category, n, seed) };
}
